---
- name: "Init Jellyfin (privileged)"
  hosts: "local_system"
  connection: "local"
  vars:
    - jellyfin: "jellyfin"
    - jellyfin_lxc: "jellyfin-lxc"


  tasks:
  - name: Create Jellyfin Container Alpine
    community.general.lxc_container:
      name: "{{ jellyfin_lxc }}"
      container_log: true
      template: "download"
      template_options: "--dist alpine --release 3.19 --arch amd64"
      state: "started"

  - name: Install Jellyfin
    ansible.builtin.command: "lxc-attach -n {{ jellyfin_lxc }} apk add {{ jellyfin }}"

  - name: Start Jellyfin Service
    ansible.builtin.command: "lxc-attach -n {{ jellyfin_lxc }} rc-service {{ jellyfin }} start
